import fs from 'node:fs/promises';
import {zip,sheet} from './xlsx-native.mjs';
import {statusName} from './status.mjs';

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
export async function makeInventoryExcel(db,file){
  const linked=new Set(db.physicalBooks.map(b=>b.legacyRecordId).filter(Boolean));
  const rows=[
    ...db.physicalBooks.map(b=>{const legacy=db.legacyRecords.find(x=>x.recordId===b.legacyRecordId);return [b.physicalId,b.acquiredDateRaw||legacy?.registeredDateRaw||'',b.titleCanonical,b.volume||'',b.publisherCanonical,b.noteRawOverride?(b.noteRaw||''):legacy?.noteRawEdited?(legacy.noteRaw||''):(b.noteRaw||legacy?.noteRaw||''),statusName(b.status)];}),
    ...db.legacyRecords.filter(b=>!linked.has(b.recordId)).map(b=>[b.legacyLedgerId,b.registeredDateRaw||'',b.titleCanonical,b.volume||'',b.publisherCanonical,b.noteRaw||'',statusName('UNKNOWN')])
  ];
  const standard=id=>/^\d{4}-\d{4}$/.test(id);
  rows.sort((a,b)=>standard(a[0])===standard(b[0])?String(a[0]).localeCompare(String(b[0]),'ko',{numeric:true}):standard(a[0])?-1:1);
  const physical=[['도서번호','입수일','도서명','권 번호','출판사','비고','실물 상태'],...rows];
  const sheets=[['실물원장',physical]];  const contentTypes=`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`;
  const workbook=`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map(([name],i)=>`<sheet name="${esc(name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`;
  const workbookRels=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
  const styles=`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Malgun Gothic"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Malgun Gothic"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF173D66"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>`;
  const files=[['[Content_Types].xml',contentTypes],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml',workbook],['xl/_rels/workbook.xml.rels',workbookRels],['xl/styles.xml',styles],...sheets.map(([,rows],i)=>[`xl/worksheets/sheet${i+1}.xml`,sheet(rows,[18,18,36,14,30,30,16])])];
  await fs.writeFile(file,zip(files));
}
