import fs from 'node:fs/promises';
import {zip,sheet} from './xlsx-native.mjs';

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
export async function makeInventoryExcel(db,file){
  const physical=[['실물번호','과거 장부번호','도서명','출판사','권','입수일 원문','상태','번호표 상태','메모','생성일','변경일'],
    ...db.physicalBooks.map(b=>[b.physicalId,db.legacyRecords.find(x=>x.recordId===b.legacyRecordId)?.legacyLedgerId||'',b.titleCanonical,b.publisherCanonical,b.volume||'',b.acquiredDateRaw||'',b.status,b.labelStatus,b.note||'',b.createdAt,b.updatedAt])];
  const legacy=[['원본 시트','원본 행','과거 장부번호','등록일 원문','도서명 원문','도서명 정리','출판사 원문','출판사 정리','권수 원문','비고 원문','저자 원문','위치 원문'],
    ...db.legacyRecords.map(r=>[r.sourceSheet,r.sourceRow,r.legacyLedgerId,r.registeredDateRaw,r.titleRaw,r.titleCanonical,r.publisherRaw,r.publisherCanonical,r.quantityRaw,r.noteRaw,r.authorRaw,r.locationRaw])];
  const disposal=[['실물번호','과거 장부번호','도서명','폐기일시 (UTC)','메모'],...db.disposals.filter(x=>x.physicalId).map(d=>[d.physicalId,db.legacyRecords.find(x=>x.recordId===d.legacyRecordId)?.legacyLedgerId||'',d.title,d.at,d.note||''])];
  const sheets=[['실물원장',physical],['과거장부',legacy],['폐기기록',disposal]];
  const contentTypes=`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`;
  const workbook=`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map(([name],i)=>`<sheet name="${esc(name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`;
  const workbookRels=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
  const styles=`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Malgun Gothic"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Malgun Gothic"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF173D66"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>`;
  const files=[['[Content_Types].xml',contentTypes],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml',workbook],['xl/_rels/workbook.xml.rels',workbookRels],['xl/styles.xml',styles],...sheets.map(([,rows],i)=>[`xl/worksheets/sheet${i+1}.xml`,sheet(rows,rows[0].map((_,n)=>n===2||n===4?32:20))])];
  await fs.writeFile(file,zip(files));
}
